### ISSUE TITLE
Further automate tests

### ISSUE THREAD

**Issue by forsyth2** [E3SM-Project/zppy#516]
#440 provides step-by-step directions for testing `zppy` for release, but can we go further than that? I.e., can we automate all those steps?

**Comment by forsyth2** [comment]
Resources suggested by @tomvothecoder:

CI/CD runners on HPC machines instead of on cloud:

- [About self-hosted runners - GitHub Docs](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/about-self-hosted-runners) 
- [GitLab Runner | GitLab](https://docs.gitlab.com/runner/)

**Comment by forsyth2** [comment]
@chengzhuzhang This is an initial attempt at automating the steps from https://e3sm-project.github.io/zppy/_build/html/main/dev_guide/release_testing.html -- specifically just the `a. test dev` steps, since that is more useful in the near-term. Once I get that working, I'm planning to make a different script for the other two cases.

There's a number of issues in fully automating this workflow. See the #TODO in-line comments.

**Comment by chengzhuzhang** [comment]
Thank you for getting to it. I think this will benefit in the long run, we can try to get this in for next unified. In terms of time-line, let's try prioritize those user-facing features (i.e. land support, zstash update, cdat migration) the land support needs lots of interaction with science team to finalize.

**Comment by forsyth2** [comment]
Yes, that timeline sounds good to me. I just wanted to get an idea of what issues we would face here.

**Comment by forsyth2** [comment]
#628 added 20 unit tests. Integration tests are really where we need further automation. Further action items:

- [ ] Address the `TODO` items in #520. If we can get those steps automated, then we can effectively automate the entire process described at https://docs.e3sm.org/zppy/_build/html/main/dev_guide/release_testing.html
- [ ] Once #520 is merged, we'll have a process we can run automatically every week. Ideally, we could set up some sort of `cron` process to run the Weekly tests weekly (rather than manually running them weekly).
- [ ] Once the weekly tests are running automatically, it would further help to run some of the `min-case` `cfg` files automatically as well. Specifically, it would be great to have some sort of "if `file` was changed in this PR or recent commit history, then run `min-case-X` cfg" setup.
- [ ] Look into mocking external dependencies rather than relying on real data paths, which can be finicky. #629 describes this further

**Comment by forsyth2** [comment]
@tomvothecoder  noted `--y` on mamba may allow automatic bypass of the `y/n` user prompts.

**Comment by forsyth2** [comment]
An extension of this functionality would be to run the image checker on all the "min-case" `cfg`s too. Those cover more specific workflows/use cases, but aren't necessarily covered by the single comprehensive `cfg`s (after all, one `cfg` can only have so many settings). However, we really would need the whole testing framework automated end-to-end first (i.e., including running `zppy` on every single `cfg`), with no manual steps, for this to be feasible.

**Comment by forsyth2** [comment]
> after all, one `cfg` can only have so many settings

Examples: 
- Test `vars` both set to an explicit variable list and to `""` (i.e., run all variables).
- Test `global_time_series` both with and without the Viewers (e.g., `make_viewer = True`)

**Comment by forsyth2** [comment]
Note the above two test cases are covered by "min-case" `cfg` files in https://github.com/E3SM-Project/zppy/pull/697

**Comment by forsyth2** [comment]
- [ ] Improve file writing logic in to`test_images.py`:
```python
    diff_subdir = f"{diff_dir}/{task}"
    if os.path.exists(diff_subdir):
        # Write missing and mismatched images to files
        missing_images_file = f"{diff_subdir}/missing_images.txt"
        if os.path.exists(missing_images_file):
            os.remove(missing_images_file)
        for missing_image in test_results.file_list_missing:
            with open(missing_images_file, "a") as f:
                f.write(f"{missing_image}\n")
        mismatched_images_file = f"{diff_subdir}/mismatched_images.txt"
        if os.path.exists(mismatched_images_file):
            os.remove(mismatched_images_file)
        for mismatched_image in test_results.file_list_mismatched:
            with open(mismatched_images_file, "a") as f:
                f.write(f"{mismatched_image}\n")
        # Create image diff grid
        # make_image_diff_grid(diff_subdir)
    else:
        print(f"Diff subdir {diff_subdir} does not exist.")
    return test_results
```
1. If `diff_subdir` doesn't exist, and `file_list_missing != []` make it. (It won't exist if there are no mismatched images, but we'll still need it to print missing images).
2. Open the file at once, and loop inside it. (`with` before `for`).

**Comment by forsyth2** [comment]
- [ ] Add some sort of comparison of expected results across machines. The total number of images should be matching up. How to do this? Only ever update Chrysalis's expected results and `rsync` those to Compy and Perlmutter for testing (rather than updating expected results on all machines)?

**Comment by xylar** [comment]
I don't think this is needed as a general new testing requirement, just to debug the current Compy issues.
