### ISSUE TITLE
Epic: improve testing framework

### ISSUE THREAD

**Issue by forsyth2** [E3SM-Project/zppy#553]
### Request criteria

- [X] I searched the [zppy GitHub Discussions](https://github.com/E3SM-Project/zppy/discussions) to find a similar question and didn't find it.
- [X] I searched the [zppy documentation](https://e3sm-project.github.io/zppy).
- [X] This issue does not match the other templates (i.e., it is not a bug report, documentation request, feature request, or a question.)

### Issue description

`zppy` testing could benefit from a number of improvements.

Currently open "Testing" issues, ranked by priority:

- [ ] #517 
- [ ] #537
- [ ] #549. Supposedly simple fix -- will need to test.
- [ ] #530. This is annoying but not a huge problem. I just have to expect that the test will always fail because the `unique_id` is different for each test run. In theory, simple fix.
- [ ] #536
- [ ] #552. I anticipate this being a challenge. All the expected files/images will need to be changed. Perhaps this could be paired with #536.
- [ ] #516. This is a nice-to-have. The testing-for-release process is tedious, but there are now directions (https://e3sm-project.github.io/zppy/_build/html/main/dev_guide/release_testing.html). That said, it is easy to miss something when going through the steps manually.
- [ ] #104. This isn't strictly necessary, but would somewhat improve test quality.
- [ ] #93. This may no longer be relevant since we have directions to generate official expected results for each release. E.g., https://github.com/E3SM-Project/zppy/blob/main/tests/integration/generated/directions_chrysalis.md#commands-to-generate-official-expected-results-for-a-release

The following would be made irrelevant by #536, since they involve changing how the image testing is done:
- [ ] #540. Simple fix.
- [ ] #358
